feature/product uid
blues/note-stm32f1 pull request #4
Opened 2022-05-03 01:40 UTC by m-mcgowan

* Removes the default PRODUCT_UID and only sets it on the notecard if it is defined.
* This PR also includes a CI build for the project
* adds `note-c` to the Release build

2022-05-04 00:58 UTC, zfields requested changes

2022-05-04 00:58 UTC, zfields commented on Src/example.c
> -        if (PRODUCT_UID[0]) {
This is handled differently than the other two repositories.

2022-06-28 18:09 UTC, m-mcgowan commented on Src/example.c
> -        if (PRODUCT_UID[0]) {
Good catch. fixed.

2022-06-28 18:10 UTC, merged

2022-07-08 20:44 UTC, m-mcgowan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Development Examples: remove hard-coded PRODUCT_UIDs from sample apps and example repos.](https://trello.com/c/gXVvrnf3/41-development-examples-remove-hard-coded-productuids-from-sample-apps-and-example-repos)